WebApp/Controllers/BillingController.cs
using System;
using System.Web.Mvc;
using WebApp.Classes;
using WebApp.Services;
using Models.Models;
using System.Configuration;

namespace WebApp.Controllers
{
    [Authorize]
    public class BillingController : Controller
    {
        public ActionResult BillingSettings(int pageIndex = 1, string sortColumn = "BillingPeriodName", string sortDirection = "DESC", bool hideRevoked = false)
        {
            var user = new UserCookie().Get().User;
            var response = new BillingService().GetBSettingList(new Store() { ID = user.StoreID }, pageIndex, Convert.ToInt32(ConfigurationManager.AppSettings.Get("PageSize")), sortColumn, sortDirection, hideRevoked);

            if (response.ErrorNumber > 0)
            {
                return RedirectToAction("StoreManagement", "Store");
            }

            ViewBag.hideRevoked = hideRevoked;

            return View(response.BSettingList);
        }

        public PartialViewResult CreateBSetting()
        {
            return PartialView("EditBSettingPartial", new BSetting() { ID = 0, Date = DateTime.Now, LastBilledDate = DateTime.Now });
        }

        [HttpPost]
        public ActionResult CreateBSetting(BSetting model)
        {
            if (ModelState.IsValid)
            {
                var cookie = new UserCookie().Get().User;
                model.UserUpdated = cookie.UserID;
                model.StoreID = cookie.StoreID;

                var response = new BillingService().CreateBSetting(model);

                if (response.ErrorNumber > 0)
                {
                    return JavaScript(Statics.GetWarningWindow(response.ErrorMessage));
                }
            }
            else
            {
                return JavaScript(Statics.GetWarningWindow("The form you're trying to submit containts validation errors!"));
            }

            return JavaScript(String.Format("window.location.href='{0}{1}'", this.HttpContext.Request.ApplicationPath, "/Billing/BillingSettings"));
        }

        public PartialViewResult EditViewBSetting(long? id)
        {
            var model = new BSetting();

            if (id != null && id > 0)
            {
                model = new BillingService().GetBSetting(new BSetting() { ID = (long)id }).BSetting;
            }

            return PartialView("EditBSettingPartial", model);
        }

        [HttpPost]
        public ActionResult EditBSetting(BSetting model)
        {
            if (ModelState.IsValid)
            {
                var cookie = new UserCookie().Get().User;
                model.UserUpdated = cookie.UserID;

                var response = new BillingService().UpdateBSetting(model);

                if (response.ErrorNumber > 0)
                {
                    return JavaScript(Statics.GetWarningWindow(response.ErrorMessage));
                }
            }
            else
            {
                return JavaScript(Statics.GetWarningWindow("The form you're trying to submit containts validation errors!"));
            }

            return JavaScript(String.Format("window.location.href='{0}{1}'", this.HttpContext.Request.ApplicationPath, "/Billing/BillingSettings"));
        }

        public ActionResult Revoke(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new BillingService().ChangeBSettingStatus(new BSetting() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = true });

            return RedirectToAction("BillingSettings");
        }

        public ActionResult Activate(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new BillingService().ChangeBSettingStatus(new BSetting() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = false });

            return RedirectToAction("BillingSettings");
        }
    }
}

WebApp/Controllers/CouponController.cs
using System;
using System.Configuration;
using System.Web.Mvc;
using Models.Models;
using WebApp.Services;
using WebApp.Classes;

namespace WebApp.Controllers
{
    [Authorize]
    public class CouponController : Controller
    {
        public ActionResult CouponSettings(long? id, int pageIndex = 1, string sortColumn = "ID", string sortDirection = "DESC", bool hideRevoked = false)
        {
            if (id == null)
            {
                var user = new UserCookie().Get().User;

                var domain = new DomainService().GetStoreIPList(new Store() { ID = user.StoreID }, 1, 1, "Name", "ASC").DomainList.List;

                if (domain.Count > 0)
                {
                    id = domain[0].ID;
                }
                else
                {
                    return RedirectToAction("DomainManagement", "Domain");
                }
            }

            ViewBag.DomainID = id;

            var model = new CouponService().GetCouponList(new Domain() { ID = (long)id }, pageIndex, Convert.ToInt32(ConfigurationManager.AppSettings.Get("PageSize")), sortColumn, sortDirection, hideRevoked).CouponList;

            ViewBag.hideRevoked = hideRevoked;

            return View(model);
        }

        public ActionResult ChangeDomain(long id)
        {
            return RedirectToAction("CouponSettings", new { id = id });
        }

        public PartialViewResult CreateCoupon(long id)
        {
            return PartialView("EditCouponPartial", new Coupon() { ID = 0, DomainID = id, ExpirationDate = DateTime.Now });
        }

        [HttpPost]
        public ActionResult CreateCoupon(Coupon model)
        {
            if (ModelState.IsValid)
            {
                var cookie = new UserCookie().Get().User;
                model.UserUpdated = cookie.UserID;

                var response = new CouponService().CreateCoupon(model);

                if (response.ErrorNumber > 0)
                {
                    return JavaScript(Statics.GetWarningWindow(response.ErrorMessage));
                }
            }
            else
            {
                return JavaScript(Statics.GetWarningWindow("The form you're trying to submit containts validation errors!"));
            }

            return JavaScript(String.Format("window.location.href='{0}{1}'", this.HttpContext.Request.ApplicationPath, "/Coupon/CouponSettings"));
        }

        public PartialViewResult EditViewCoupon(long? id)
        {
            var model = new Coupon();

            if (id != null && id > 0)
            {
                model = new CouponService().GetCoupon(new Coupon() { ID = (long)id }).Coupon;
            }

            return PartialView("EditCouponPartial", model);
        }

        [HttpPost]
        public ActionResult EditCoupon(Coupon model)
        {
            if (ModelState.IsValid)
            {
                var cookie = new UserCookie().Get().User;
                model.UserUpdated = cookie.UserID;

                var response = new CouponService().UpdateCoupon(model);

                if (response.ErrorNumber > 0)
                {
                    return JavaScript(Statics.GetWarningWindow(response.ErrorMessage));
                }
            }
            else
            {
                return JavaScript(Statics.GetWarningWindow("The form you're trying to submit containts validation errors!"));
            }

            return JavaScript(String.Format("window.location.href='{0}{1}'", this.HttpContext.Request.ApplicationPath, "/Coupon/CouponSettings"));
        }

        public ActionResult Revoke(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new CouponService().ChangeCouponStatus(new Coupon() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = true });

            return RedirectToAction("CouponSettings");
        }

        public ActionResult Activate(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new CouponService().ChangeCouponStatus(new Coupon() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = false });

            return RedirectToAction("CouponSettings");
        }
    }
}

WebApp/Controllers/StoreController.cs
using System.Web.Mvc;
using WebApp.Services;
using WebApp.Classes;
using Models.Models;
using System;

namespace WebApp.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        public ActionResult StoreManagement(long? id, bool hideRevoked = false)
        {
            var user = new UserCookie().Get().User;
            var model = new StoreService().GetStoreListByUser(user, hideRevoked).StoreList;

            ViewBag.hideRevoked = hideRevoked;
            ViewBag.storeId = id.HasValue ? id : 0;

            return View(model);
        }

        public PartialViewResult EditViewStore(long? id)
        {
            var model = new Store();

            if (id != null && id > 0)
            {
                model = new StoreService().GetStore(new Store() { ID = (long)id }).Store;
            }

            return PartialView("EditStorePartial", model);
        }

        [HttpPost]
        public ActionResult EditStore(Store model)
        {
            if (ModelState.IsValid)
            {
                var cookie = new UserCookie().Get().User;
                model.UserUpdated = cookie.UserID;

                var response = new StoreService().UpdateStore(model);

                if (response.ErrorNumber > 0)
                {
                    return JavaScript(Statics.GetWarningWindow(response.ErrorMessage));
                }
            }
            else
            {
                return JavaScript(Statics.GetWarningWindow("The form you're trying to submit containts validation errors!"));
            }

            return JavaScript(String.Format("window.location.href='{0}{1}/{2}'", this.HttpContext.Request.ApplicationPath, "/Store/StoreManagement", model.ID));
        }

        public ActionResult AddStore(long id)
        {
            var model = new StoreService().AddStore(new Store() { ParentID = id, ContractExpirationDate = DateTime.Now });

            return RedirectToAction("StoreManagement", new { id = model.Store.ID });
        }

        public ActionResult Revoke(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new StoreService().ChangeStoreStatus(new Store() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = true });

            return RedirectToAction("StoreManagement", new { id = id });
        }

        public ActionResult Activate(long id)
        {
            var cookie = new UserCookie().Get().User;
            var response = new StoreService().ChangeStoreStatus(new Store() { ID = id, UserUpdated = cookie.UserID, RevokeStatus = false });

            return RedirectToAction("StoreManagement", new { id = id });
        }
    }
}

WebApp/Views/Shared/ChargeDetails.cshtml
@model Models.Models.ChargeList
@using WebApp.Classes

@{
    ViewBag.Title = "Charges";
    var rights = ViewBag.rights;
}

@Scripts.Render("~/scripts/jquery.fixheadertable.js")

<table width="100%">
    <tbody>
        <tr>
            <td width="100%" valign="top">
                         
                    <div style="border-style: solid; border-width: 1px; border-color: #DDDDDD"> 
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>
                                TransactionID
                            </th>
                            <th>
                                Created
                            </th>
                            <th>
                                Updated
                            </th>
                            <th>
                                Number
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                Amount
                            </th>
                            <th>
                                CustomerProfileID
                            </th>
                            <th>
                                CustomerPaymentProfileID
                            </th>
                            <th>
                                TransID
                            </th>
                            <th>
                                TranType
                            </th>
                            <th>
                                retCode
                            </th>
                            <th>
                                ErrMsg
                            </th>
                            <th>
                                CPReturnCode
                            </th>
                            <th>
                                CPPReturnCode
                            </th>
                            <th>
                                TranReturnCode
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @{
                            foreach (var charge in Model.List)
                            {
                                <tr>
                                    <td>
                                        @charge.TransactionID
                                    </td>
                                    <td>
                                        @charge.Created.ToString("MM/dd/yyyy hh:mm tt")
                                    </td>
                                    <td>
                                        @charge.Updated.ToString("MM/dd/yyyy hh:mm tt")
                                    </td>
                                    <td>
                                        @charge.Number
                                    </td>
                                    <td>
                                        @charge.Description
                                    </td>
                                    <td>
                                        @charge.Amount.ToString("###,###,###.00")
                                    </td>
                                    <td>
                                        @charge.CustomerProfileID
                                    </td>
                                    <td>
                                        @charge.CustomerPaymentProfileID
                                    </td>
                                    <td>
                                        @charge.TransID
                                    </td>
                                    <td>
                                        @charge.TranType
                                    </td>
                                    <td>
                                        @charge.retCode
                                    </td>
                                    <td>
                                        @charge.ErrMsg
                                    </td>
                                    <td>
                                        @charge.CPReturnCode
                                    </td>
                                    <td>
                                        @charge.CPPReturnCode
                                    </td>
                                    <td>
                                        @charge.TranReturnCode
                                    </td>
                                </tr>
                            }
                        }
                            <tr>
                                <td colspan="13">
                                </td>
                                <td colspan="2" style="text-align: right">
                                    <form ></form>
                                    <h5>Records: @Model.ResultCount</h5>
                                </td>
                            </tr>
                        </tbody>                          
                    </table>
                    </div>
            </td>
        </tr>
    </tbody>
</table>      

WebApp/Views/Shared/DashboardPartial.cshtml
@using WebApp.Classes;
@using Models.Models;

@{
    var user = new UserCookie().Get().User;

    var domains = new WebApp.Services.DomainService().GetStoreIPList(new Store() { ID = user.StoreID }, 1, 1000000, "Name", "ASC", true).DomainList;
    var domainList = new SelectList(domains.List, "ID", "Name");        
    
    var groups = new List<KeyValuePair<string, string>>();
    groups.Add(new KeyValuePair<string, string>("6", "Yearly"));
    groups.Add(new KeyValuePair<string, string>("1", "Hourly"));
    groups.Add(new KeyValuePair<string, string>("2", "Daily"));
    groups.Add(new KeyValuePair<string, string>("3", "Weekly"));
    groups.Add(new KeyValuePair<string, string>("4", "Monthly"));
    groups.Add(new KeyValuePair<string, string>("5", "Quarterly"));
    
    var groupList = new SelectList(groups, "Key", "Value");
}

@Styles.Render("~/Content/themes/base/jquery.ui.all.css")
@Styles.Render("~/Content/themes/base/jquery.ui.datepicker.css")    

@Scripts.Render("~/scripts/jquery-ui-1.8.11.min.js")
@Scripts.Render("~/scripts/app/gchart.js")
@Scripts.Render("http://www.google.com/jsapi")

@Scripts.Render("~/scripts/app/" + Path.GetFileNameWithoutExtension(Server.MapPath(VirtualPath)) + ".js")

@Html.Hidden("userID", user.UserID)
@Html.Hidden("storeID", user.StoreID)

<form></form>
<table width="100%" border="0">
    <tr>
        <td valign="top" width="25%">
            Domain: 
            @Html.DropDownList("domainSelect", domainList, new { @class = "input-medium", @id = "domainSelect" })
        </td>
        <td valign="top" width="20%">
            Group By:
            @Html.DropDownList("groupSelect", groupList, new { @class = "input-small", @id = "groupSelect" })
        </td>
        <td valign="top" width="15%">
            from:
            <input type="text" class="datePicker start"/>
        </td>
        <td valign="top" width="15%">
            to:
            <input type="text" class="datePicker end"/>
        </td>
        <td valign="top" align="right">
            <button type="button" class="btn btn-inverse active" id="chart"><i class="icon-align-left icon-white"></i> Chart</button>
            <button type="button" class="btn btn-inverse" id="table"><i class="icon-list icon-white"></i> Table</button>
            <button type="button" class="btn btn-inverse" id="csv"><i class="icon-download icon-white"></i> CSV</button>
        </td>
    </tr>
</table>

<div id="divData" style="overflow: hidden">
</div>

WebApp/Views/Shared/EditBSettingPartial.cshtml
@model Models.Models.BSetting

@{
    var periods = new WebApp.Services.ServiceService().GetLookUp("BillingPeriod");
    var periodList = new SelectList(periods.LookUpList, "Key", "Value");

    var types = new WebApp.Services.ServiceService().GetLookUp("BillingType");
    var typeList = new SelectList(types.LookUpList, "Key", "Value");
}

<script>
    $(document).ready(function () {
        $('#Date').attr('readonly', 'readonly');
        $('#Date').css('cursor', 'pointer');
        $('#Date').addClass('input-small');

        $('#Date').datepicker({
            showAnim: 'slideDown',
            dateFormat: 'mm/dd/yy'
        });
    });
</script>

@using (Ajax.BeginForm(Model.ID == 0 ? "CreateBSetting" : "EditBSetting", "Billing", null, new AjaxOptions(), new { @id = "formBSetting", @class = "form-horizontal" }))
{        
        <fieldset style="height: 440px; border-style: ridge; border-width: 1px; border-color: #DDDDDD;">
                @Html.ValidationSummary()

                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.StoreID)

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.PeriodID)</label>
                    <div class="controls">@Html.DropDownListFor(m => m.PeriodID, periodList, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.TypeID)</label>
                    <div class="controls">@Html.DropDownListFor(m => m.TypeID, typeList, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Unit)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.Unit, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Rate)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.Rate, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Date)</label>
                    <div class="controls"><div class="input-append">@Html.EditorFor(m => m.Date, "", new { @id = "datePicker", @class = "datePicker" })</div></div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.CN)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.CN, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.CE)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.CE, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.CustomerPaymentProfileID)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.CustomerPaymentProfileID, new { @class = "input-small", @readonly = "true" })</div>
                </div>

    </fieldset>
        <br />
    
    {
        var rights = new WebApp.Classes.UserRights("Billing Settings");

        if (rights.FullControl || rights.Editable)
        { 
                    <div class="">
                        @if (!Model.RevokeStatus)
                        {
                            if (Model.ID == 0)
                            {
                                <button type="submit" class="btn btn-inverse" id="createBSetting"><i class="icon-ok icon-white"></i> Create</button>            
                            }
                            else
                            { 
                                <button type="submit" class="btn btn-inverse" id="updateBSetting"><i class="icon-ok icon-white"></i> Update</button>                                        
                            }
                        }
                        @if (Model.ID != 0)
                        {
                            if (Model.RevokeStatus)
                            {
                                <button type="button" class="btn btn-inverse" id="activate"><i class="icon-repeat icon-white"></i> Activate</button>
                            }
                            else
                            {                            
                                <button type="button" class="btn btn-inverse" id="revoke"><i class="icon-remove icon-white"></i> Revoke</button>
                            }
                        }
                    </div>
        }
    }

}

WebApp/Views/Shared/EditCouponPartial.cshtml
@model Models.Models.Coupon

@{
    var types = new WebApp.Services.ServiceService().GetLookUp("CouponType");
    var typeList = new SelectList(types.LookUpList, "Key", "Value");
}

<script>
    $(document).ready(function () {
        $("#ExpirationDate").attr('readonly', 'readonly');
        $("#ExpirationDate").css('cursor', 'pointer');
        $("#ExpirationDate").addClass('input-small');

        $("#ExpirationDate").datepicker({
            showAnim: 'slideDown',
            dateFormat: 'mm/dd/yy'
        });
    });
</script>

@using (Ajax.BeginForm(Model.ID == 0 ? "CreateCoupon" : "EditCoupon", "Coupon", null, new AjaxOptions(), new { @id = "formCoupon", @class = "form-horizontal" }))
{        
        <fieldset style="height: 500px; border-style: ridge; border-width: 1px; border-color: #DDDDDD;">
                @Html.ValidationSummary()

                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.DomainID)

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.eCommCouponID)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.eCommCouponID, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Description)</label>
                    <div class="controls">@Html.TextAreaFor(m => m.Description, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Value)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.Value, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.MinOrderAmount)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.MinOrderAmount, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.MaxOrderAmount)</label>
                    <div class="controls">@Html.TextBoxFor(m => m.MaxOrderAmount, new { @class = "input-small" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.TypeID)</label>
                    <div class="controls">@Html.DropDownListFor(m => m.TypeID, typeList, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.Message)</label>
                    <div class="controls">@Html.TextAreaFor(m => m.Message, new { @class = "input-medium" })</div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.ExpirationDate)</label>
                    <div class="controls"><div class="input-append">@Html.EditorFor(m => m.ExpirationDate, "", new { @id = "datePicker", @class = "datePicker" })</div></div>
                </div>

                <div class="control-group">    
                    <label class="control-label" for="input01">@Html.LabelFor(m => m.LimitedNumber)</label>
                    <div class="controls">@Html.EditorFor(m => m.LimitedNumber) @Html.TextBoxFor(m => m.Uses, new { @class = "input-small" })</div>
                </div>

        </fieldset>            
    <br />
    {
        var rights = new WebApp.Classes.UserRights("Coupon Settings");

        if (rights.FullControl || rights.Editable)
        { 
                    <div class="">
                        @if (!Model.RevokeStatus)
                        {
                            if (Model.ID == 0)
                            {
                                <button type="submit" class="btn btn-inverse" id="createCoupon"><i class="icon-ok icon-white"></i> Create</button>            
                            }
                            else
                            { 
                                <button type="submit" class="btn btn-inverse" id="updateCoupon"><i class="icon-ok icon-white"></i> Update</button>                                        
                            }
                        }
                        @if (Model.ID != 0)
                        {
                            if (Model.RevokeStatus)
                            {
                                <button type="button" class="btn btn-inverse" id="activate"><i class="icon-repeat icon-white"></i> Activate</button>
                            }
                            else
                            {                            
                                <button type="button" class="btn btn-inverse" id="revoke"><i class="icon-remove icon-white"></i> Revoke</button>
                            }
                        }
                    </div>
        }
    }
}

WebApp/Views/Shared/PasswordReminderPartial.cshtml
@model Models.Models.PasswordReminder

@using (Ajax.BeginForm("RetrievePassword", "Account", null, new AjaxOptions() { HttpMethod = "POST" }, new { @class = "form-horizontal" }))
{       
    <fieldset>
        <legend><img src="~/Images/glyphicons/png/glyphicons_152_new_window.png" /> Retrieve Password</legend>

        <div class="alert alert-info">
            If you want your password to be sent to your registration email address, please fill out and submit the form below.
        </div>

        <div class="control-group">    
            <label class="control-label" for="input01">@Html.LabelFor(m => m.UserEmail)</label>
            <div class="controls">@Html.TextBoxFor(m => m.UserEmail, new { @readonly = true })</div>
        </div>

        <div class="control-group">    
            <label class="control-label" for="input01">@Html.LabelFor(m => m.SecureQuestion)</label>
            <div class="controls">@Html.TextBoxFor(m => m.SecureQuestion, new { @readonly = true, @class = "input-xxlarge" })</div>
        </div>

        <div class="control-group">    
            <label class="control-label" for="input01">@Html.LabelFor(m => m.SecureAnswer)</label>
            <div class="controls">@Html.TextBoxFor(m => m.SecureAnswer, new { @class = "input-xxlarge" })</div>
        </div>

        <div class="controls btn-group">    
            <button type="submit" class="btn btn-inverse"><i class="icon-ok icon-white"></i> Send Password</button>            
        </div>    

    </fieldset>
}